### ISSUE TITLE
Custom songs folder directory

### ISSUE THREAD

**Issue by lukemagdalin** [TcNobo/TcNo-osu-Cleaner#4]
I have my songs folder located on a separate disk from the main osu directory, and while running this program I get an error stating that the program cannot find the songs folder. To fix this you could read the osu!.username.cfg file and the 7th line will say where the songs folder is located.

**Comment by TcNobo** [comment]
This feature is now added and included in v2.3, available here: https://github.com/TcNobo/TcNo-osu-Cleaner/releases/tag/2.3
Do let me know if you have any issues.
